package com.baicheng.oauth2resourceserver.mapper;

import com.baicheng.oauth2resourceserver.model.ProductPO;
import com.baicheng.oauth2resourceserver.model.ProductPOExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    long countByExample(ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    int deleteByExample(ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    @Delete({
        "delete from t_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    @Insert({
        "insert into t_product (version, is_deleted, ",
        "name)",
        "values (#{version,jdbcType=INTEGER}, #{isDeleted,jdbcType=BIT}, ",
        "#{name,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ProductPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    int insertSelective(ProductPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    List<ProductPO> selectByExampleWithRowbounds(ProductPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    List<ProductPO> selectByExample(ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    @Select({
        "select",
        "id, version, is_deleted, name",
        "from t_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.baicheng.oauth2resourceserver.mapper.ProductMapper.BaseResultMap")
    ProductPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductPO record, @Param("example") ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    int updateByExample(@Param("record") ProductPO record, @Param("example") ProductPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    int updateByPrimaryKeySelective(ProductPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Wed Feb 27 21:04:45 CST 2019
     */
    @Update({
        "update t_product",
        "set version = #{version,jdbcType=INTEGER},",
          "is_deleted = #{isDeleted,jdbcType=BIT},",
          "name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductPO record);
}